#!/usr/bin/env python3
"""Generate README.md from GitHub starred repositories grouped by month."""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


GITHUB_API = "https://api.github.com/user/starred"
ACCEPT_HEADER = "application/vnd.github.v3.star+json"
PER_PAGE = 100
DEFAULT_ACTION_URL = "https://github.com/erbanku/action-stars"
LICENSE_FOOTER = """## License

[![CC0](http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg)](https://creativecommons.org/publicdomain/zero/1.0/)

To the extent possible under law, [erbanku](https://github.com/erbanku) has waived all copyright and related or neighboring rights to this work."""


def fetch_starred(token: str) -> list[dict]:
    stars: list[dict] = []
    page = 1

    while True:
        url = f"{GITHUB_API}?per_page={PER_PAGE}&page={page}"
        request = urllib.request.Request(
            url,
            headers={
                "Accept": ACCEPT_HEADER,
                "Authorization": f"Bearer {token}",
                "User-Agent": "erbanku-action-stars",
            },
        )

        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                payload = json.load(response)
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"GitHub API error {exc.code}: {body}") from exc

        if not payload:
            break

        for item in payload:
            repo = item.get("repo") or {}
            starred_at = item.get("starred_at")
            if not starred_at:
                continue

            stars.append(
                {
                    "starred_at": starred_at,
                    "full_name": repo.get("full_name", ""),
                    "html_url": repo.get("html_url", ""),
                    "description": repo.get("description") or "",
                }
            )

        if len(payload) < PER_PAGE:
            break
        page += 1

    return stars


def month_key(starred_at: str) -> str:
    dt = datetime.fromisoformat(starred_at.replace("Z", "+00:00"))
    return dt.astimezone(timezone.utc).strftime("%Y-%m")


def escape_description(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip())


def format_repo_line(star: dict) -> str:
    name = star["full_name"]
    url = star["html_url"] or f"https://github.com/{name}"
    description = escape_description(star["description"])
    if description:
        return f"- [{name}]({url}) - {description}"
    return f"- [{name}]({url})"


def render_month_section(
    lines: list[str],
    month: str,
    month_stars: list[dict],
    *,
    heading_level: int,
) -> None:
    heading = "#" * heading_level
    lines.extend([f"{heading} {month} ({len(month_stars)})", ""])
    for star in sorted(month_stars, key=lambda item: item["starred_at"], reverse=True):
        lines.append(format_repo_line(star))
    lines.append("")


def build_readme(stars: list[dict]) -> str:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for star in stars:
        grouped[month_key(star["starred_at"])].append(star)

    current_year = datetime.now(timezone.utc).strftime("%Y")
    title = os.environ.get("README_TITLE", "GitHub Stars")
    include_attribution = os.environ.get("INCLUDE_ATTRIBUTION", "true").lower() == "true"
    action_url = os.environ.get("ACTION_URL", DEFAULT_ACTION_URL)

    lines = [f"# {title}", ""]

    if include_attribution:
        lines.extend(
            [
                f"> A curated list of my GitHub stars! Generated by [Stars]({action_url}).",
                "",
            ]
        )

    years: dict[str, list[str]] = defaultdict(list)
    for month in sorted(grouped.keys(), reverse=True):
        years[month[:4]].append(month)

    for year in sorted(years.keys(), reverse=True):
        year_months = years[year]
        if year == current_year:
            for month in year_months:
                render_month_section(lines, month, grouped[month], heading_level=2)
            continue

        year_count = sum(len(grouped[month]) for month in year_months)
        lines.extend(["<details>", f"<summary>{year} ({year_count})</summary>", ""])
        for month in year_months:
            render_month_section(lines, month, grouped[month], heading_level=3)
        lines.extend(["</details>", ""])

    if os.environ.get("INCLUDE_LICENSE_FOOTER", "false").lower() == "true":
        lines.extend(["", LICENSE_FOOTER, ""])

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("GITHUB_TOKEN is required", file=sys.stderr)
        return 1

    output = Path(os.environ.get("OUTPUT_PATH", "README.md"))

    stars = fetch_starred(token)
    readme = build_readme(stars)
    output.write_text(readme, encoding="utf-8")
    print(
        f"Wrote {len(stars)} stars across "
        f"{len(set(month_key(s['starred_at']) for s in stars))} months to {output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
